services:
  - type: web
    name: lendify-prelaunch
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lendify-db
          property: connectionString

databases:
  - name: lendify-db
    databaseName: lendify
    user: lendify_user
